export const OPTIONS = {
  competitor:["TD","RBC","BMO","CIBC","Desjardins","Amex","Venn","Float","Other"],
  category:["Traditional Banking","Fintech","Other"],
  year:["2020","2021","2022","2023","2024","2025","2026","Other"],
  type:["Video","Print","Digital","Social","OOH","Website","Blog","Podcast","Event","Direct Mail","In-branch","Other"],
  entryDoor:["Freedom","Craft","Identity","Build to Exit","Multiple","None identifiable","Other"],
  experienceReflected:["Existential struggle","Validation seeking","Complexity navigation","Consolidation choice","General entrepreneurship","Not specific","Other"],
  portrait:["Dreamer","Builder","Sovereign","Architect","Multiple","None identifiable","Other"],
  richnessDefinition:["Potential","Impact","Life well-designed","Strategic capability","Financial (default)","Not addressed","Other"],
  journeyPhase:["Existential","Validation","Complexity","Consolidation","Cross-phase","Not specific","Other"],
  momentAcquisition:["Personal-to-business transition","First account setup","Digital tools config","First cash flow crisis","First LOC or credit","None","Other"],
  momentDeepening:["RM assignment/turnover","Major financing","Crisis navigation","Succession planning","Fintech adoption","None","Other"],
  momentUnexpected:["Revenue milestone","Business anniversary","Employee milestone","Peer connection","Personal life transition","None","Other"],
  clientLifecycle:["Starter","Growth","Steady","Succession","Cross-lifecycle","Not specific","Other"],
  bankRole:["Advisor","Partner","Enabler","Cheerleader","Invisible infrastructure","Community builder","Not clear","Other"],
  painPointType:["Names real problem","Aspiration territory","Product-focused only","Other"],
  languageRegister:["Owner language","Banking language","Mixed","Neither","Other"],
  channel:["Branch","Digital (web)","Digital (app)","Social media","Mass media","OOH","Direct mail","Event","Content marketing","PR","Other"],
  cta:["Visit branch","Call advisor","Use digital tool","Apply for product","Learn more","Brand only","No CTA","Other"],
  toneOfVoice:["Authoritative","Empathetic","Aspirational","Peer-level","Institutional","Playful","Urgent","Other"],
  representation:["Solo founder","Founder + team","Founder + family","Business only","Diverse mix","Corporate imagery","Other"],
  industryShown:["Construction-trades","Professional services","Food-hospitality","Retail","Tech-digital","Manufacturing","General","Other"],
  businessSize:["Micro","Core","Mid-Market","Not specified","Other"],
  brandArchetype:["Innocent","Explorer","Sage","Hero","Outlaw","Magician","Regular Guy","Lover","Jester","Caregiver","Creator","Ruler","Not identifiable","Other"],
  diffClaim:["Explicit differentiation","Implicit positioning","Interchangeable","Other"],
};

export const COMPETITOR_COLORS = {
  TD:"#059669",RBC:"#2563eb",BMO:"#0ea5e9",CIBC:"#dc2626",
  Desjardins:"#16a34a",Amex:"#2563eb",Venn:"#7c3aed",Float:"#14b8a6",
  Fintech:"#7c3aed","Traditional Banking":"#475569"
};

export const FORM_SECTIONS = [
  {title:"A. Identification",fields:[
    {key:"competitor",label:"Competitor",type:"select"},
    {key:"category",label:"Category",type:"select"},
    {key:"description",label:"Description",type:"text"},
    {key:"year",label:"Year",type:"select"},
    {key:"type",label:"Type",type:"select"},
    {key:"url",label:"URL",type:"text"},
    {key:"image_url",label:"Image URL",type:"text"},
    {key:"transcript",label:"Transcript",type:"textarea"},
  ]},
  {title:"B. Identity",fields:[
    {key:"entry_door",label:"Entry door",type:"select",optKey:"entryDoor"},
    {key:"experience_reflected",label:"Experience",type:"select",optKey:"experienceReflected"},
    {key:"portrait",label:"Portrait",type:"select"},
    {key:"richness_definition",label:"Richness",type:"select",optKey:"richnessDefinition"},
  ]},
  {title:"C. Journey",fields:[
    {key:"journey_phase",label:"Phase",type:"select",optKey:"journeyPhase"},
    {key:"client_lifecycle",label:"Lifecycle",type:"select",optKey:"clientLifecycle"},
    {key:"moment_acquisition",label:"Acquisition moment",type:"select",optKey:"momentAcquisition"},
    {key:"moment_deepening",label:"Deepening moment",type:"select",optKey:"momentDeepening"},
    {key:"moment_unexpected",label:"Unexpected moment",type:"select",optKey:"momentUnexpected"},
  ]},
  {title:"D. Brand",fields:[
    {key:"bank_role",label:"Bank role",type:"select",optKey:"bankRole"},
    {key:"pain_point_type",label:"Pain point type",type:"select",optKey:"painPointType"},
    {key:"pain_point",label:"Pain point",type:"text"},
    {key:"language_register",label:"Language",type:"select",optKey:"languageRegister"},
    {key:"main_vp",label:"Main VP",type:"text"},
    {key:"brand_attributes",label:"Attributes",type:"text"},
    {key:"emotional_benefit",label:"Emotional benefit",type:"text"},
    {key:"rational_benefit",label:"Rational benefit",type:"text"},
    {key:"r2b",label:"R2B",type:"text"},
  ]},
  {title:"E. Execution",fields:[
    {key:"channel",label:"Channel",type:"select"},
    {key:"cta",label:"CTA",type:"select"},
    {key:"tone_of_voice",label:"Tone",type:"select",optKey:"toneOfVoice"},
    {key:"representation",label:"Representation",type:"select"},
    {key:"industry_shown",label:"Industry",type:"select",optKey:"industryShown"},
    {key:"business_size",label:"Size",type:"select",optKey:"businessSize"},
    {key:"brand_archetype",label:"Archetype",type:"select",optKey:"brandArchetype"},
    {key:"diff_claim",label:"Differentiation",type:"select",optKey:"diffClaim"},
  ]},
];
