// Report content model v2 — an ordered list of blocks, each with a STABLE id.
// The id is the anchor for comments (block_id + offsets) and lets a single section be
// regenerated by replacing its blocks. Never anchor to matched text.
//
// A report's content is { v: 2, blocks: [...] }. Legacy reports are a markdown/HTML
// string or { markdown } — converted on open by fromLegacy() (a pure function).

// Block id: short, collision-resistant, human-skimmable. Not cryptographic.
let _seq = 0;
export function blockId() {
  _seq = (_seq + 1) % 1e6;
  const rand = Math.random().toString(36).slice(2, 8);
  return `blk_${rand}${_seq.toString(36)}`;
}

// Block types. Text types carry `text`; list types carry `items`; visual types carry `data`.
// The visual set is the one the v3 handoff specifies for the report document — charts are
// STRUCTURED, EDITABLE data blocks, never baked images:
//   kpi        { items:[{ label, value, caption, hero }] }        KPI row
//   bars       { items:[{ label, value, hero }], max }            ranking bars
//   split      { items:[{ label, value }] }                       stacked format split
//   heatmap    { rows:[], cols:[], cells:[[…]], hero:[r,c] }      brand × dimension
//   quadrant   { xLabel, yLabel, points:[{ label, x, y, hero }] } white-space 2×2
//   pullquote  { text, attribution }                              Klamp pull-quote
export const BLOCK_TYPES = [
  "h2", "h3", "p", "bullets", "numbered", "quote",
  "kpi", "bars", "split", "heatmap", "quadrant", "pullquote",
  "table", "case",
];
const TEXT_TYPES = new Set(["h2", "h3", "p", "quote"]);
const LIST_TYPES = new Set(["bullets", "numbered"]);
export const VISUAL_TYPES = new Set(["kpi", "bars", "split", "heatmap", "quadrant", "pullquote", "table"]);

export function makeBlock(type, { sectionKey = null, text = "", items = null, data = null, id = null } = {}) {
  const b = { id: id || blockId(), type, sectionKey };
  if (LIST_TYPES.has(type)) b.items = items || [];
  else if (TEXT_TYPES.has(type)) b.text = text;
  else b.data = data || {};
  return b;
}

export function isV2(content) {
  return content && typeof content === "object" && content.v === 2 && Array.isArray(content.blocks);
}

// Parse a markdown string into ordered blocks, tagging each with the given sectionKey.
// Handles: ## / ### headings, - / * bullets, 1. numbered, > quote, --- rule (dropped),
// blank-line-separated paragraphs. Inline markdown (bold, links, citations) is preserved
// verbatim inside text/items — the renderer handles it.
export function markdownToBlocks(md, sectionKey = null) {
  const blocks = [];
  const lines = String(md || "").replace(/\r\n/g, "\n").split("\n");
  let para = [];
  let list = null; // { type, items }
  const flushPara = () => { if (para.length) { blocks.push(makeBlock("p", { sectionKey, text: para.join(" ").trim() })); para = []; } };
  const flushList = () => { if (list && list.items.length) { blocks.push(makeBlock(list.type, { sectionKey, items: list.items })); } list = null; };
  const flushAll = () => { flushPara(); flushList(); };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) { flushAll(); continue; }
    let m;
    if ((m = line.match(/^(#{2,3})\s+(.*)$/))) { flushAll(); blocks.push(makeBlock(m[1].length === 2 ? "h2" : "h3", { sectionKey, text: m[2].trim() })); continue; }
    if (/^(-{3,}|\*{3,}|_{3,})$/.test(line.trim())) { flushAll(); continue; } // horizontal rule → drop
    if ((m = line.match(/^\s*>\s?(.*)$/))) { flushPara(); if (list && list.type !== "quote") flushList(); blocks.push(makeBlock("quote", { sectionKey, text: m[1].trim() })); continue; }
    if ((m = line.match(/^\s*[-*+]\s+(.*)$/))) { flushPara(); if (!list || list.type !== "bullets") { flushList(); list = { type: "bullets", items: [] }; } list.items.push(m[1].trim()); continue; }
    if ((m = line.match(/^\s*\d+[.)]\s+(.*)$/))) { flushPara(); if (!list || list.type !== "numbered") { flushList(); list = { type: "numbered", items: [] }; } list.items.push(m[1].trim()); continue; }
    flushList();
    para.push(line.trim());
  }
  flushAll();
  return blocks;
}

// Legacy → v2. Accepts a plain string, { markdown }, or an array of { key, title, markdown }
// sections (the shape the report routes return). Returns { v: 2, blocks: [...] }.
export function fromLegacy(content) {
  if (isV2(content)) return content;
  const blocks = [];
  if (Array.isArray(content)) {
    for (const s of content) {
      if (!s) continue;
      if (s.title) blocks.push(makeBlock("h2", { sectionKey: s.key || null, text: s.title }));
      blocks.push(...markdownToBlocks(s.markdown || s.text || "", s.key || null));
    }
  } else {
    const md = typeof content === "string" ? content : (content?.markdown || content?.text || "");
    blocks.push(...markdownToBlocks(md, null));
  }
  return { v: 2, blocks };
}

// v2 → markdown (for export / copy). Rich blocks degrade to a readable text form.
export function blocksToMarkdown(content) {
  const doc = isV2(content) ? content : fromLegacy(content);
  const out = [];
  for (const b of doc.blocks) {
    switch (b.type) {
      case "h2": out.push(`## ${b.text}`); break;
      case "h3": out.push(`### ${b.text}`); break;
      case "p": out.push(b.text); break;
      case "quote": out.push(`> ${b.text}`); break;
      case "bullets": out.push((b.items || []).map((i) => `- ${i}`).join("\n")); break;
      case "numbered": out.push((b.items || []).map((i, n) => `${n + 1}. ${i}`).join("\n")); break;
      case "table": out.push(tableToMarkdown(b.data)); break;
      case "case": out.push(caseToMarkdown(b.data)); break;
      // Visual blocks degrade to readable text for .md/.doc export (the PDF prints the
      // real HTML render, so it keeps the chart).
      case "kpi": out.push((b.data?.items || []).map((i) => `- **${i.value}** — ${i.label}${i.caption ? ` (${i.caption})` : ""}`).join("\n")); break;
      case "bars":
      case "split": out.push((b.data?.items || []).map((i) => `- ${i.label}: ${i.value}`).join("\n")); break;
      case "heatmap": out.push(tableToMarkdown({ columns: ["", ...(b.data?.cols || [])], rows: (b.data?.rows || []).map((r, i) => [r, ...((b.data?.cells || [])[i] || [])]) })); break;
      case "quadrant": out.push((b.data?.points || []).map((p) => `- ${p.label} — ${b.data?.xLabel || "x"}: ${p.x}, ${b.data?.yLabel || "y"}: ${p.y}`).join("\n")); break;
      case "pullquote": out.push(`> ${b.data?.text || ""}${b.data?.attribution ? `\n> — ${b.data.attribution}` : ""}`); break;
      default: if (b.text) out.push(b.text);
    }
  }
  return out.filter(Boolean).join("\n\n");
}

function tableToMarkdown(data = {}) {
  const cols = data.columns || [];
  const rows = data.rows || [];
  if (!cols.length) return "";
  const head = `| ${cols.join(" | ")} |`;
  const sep = `| ${cols.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${(Array.isArray(r) ? r : cols.map((c) => r[c] ?? "")).join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

function caseToMarkdown(data = {}) {
  const label = [data.brand, data.line].filter(Boolean).join(" — ") || "Case";
  return data.entryId ? `[${label}](cite:${data.entryId})` : label;
}
