// REPORT_CARDS — the catalog. One entry per report type. The Configure screen renders
// its Sections card from `sections` here, and the generation orchestrator reads `family`
// (→ weight mode) and the section list from here. Adding a report = adding an entry.
//
// weight mode is TIED TO THE FAMILY (the configurator no longer exposes it):
//   brand_signal → intent × source · performance → engagement · quality → rating.
//
// `kind`:
//   'report'  — a full multi-section engine (its own route)
//   'section' — a single flagship section extracted as a standalone deliverable
//               (generated by the flagship route with just that section on, plus the
//                optional exec/recs the analyst ticks in Configure)

export const FAMILY_WEIGHT = { brand_signal: "brand_signal", performance: "performance", quality: "quality" };

// The flagship's own sections, reused by the section-extract cards.
const FLAGSHIP_SECTIONS = [
  { key: "landscape",       title: "Category landscape",        desc: "Territories occupied and who owns what." },
  { key: "positioning",     title: "Positioning x-ray",         desc: "Expressed (Brand DNA / web) vs validated (content) — the gap." },
  { key: "hero",            title: "Hero & message consistency", desc: "Is the hero message stable over time and across channels?" },
  { key: "whitespace",      title: "White space & opportunity", desc: "Territories nobody owns → concrete opportunities." },
  { key: "exec",            title: "Executive read",            desc: "Strategic headline, ICP-lensed.", synthesis: true },
  { key: "recommendations", title: "Strategic recommendations", desc: "Prioritized, concrete actions.", synthesis: true },
];

// A section-extract card: the one core section + optional (default-on) exec & recs.
const sectionExtract = (coreKey) => {
  const core = FLAGSHIP_SECTIONS.find((s) => s.key === coreKey);
  return [
    { ...core, required: true },
    { key: "exec",            title: "Executive read",            desc: "Short framing for this focused study.", synthesis: true, optional: true, defaultOn: true },
    { key: "recommendations", title: "Recommendations",           desc: "A few concrete actions.",              synthesis: true, optional: true, defaultOn: true },
  ];
};

export const REPORT_CARDS = {
  // ── Full engines (built) ──
  strategic_positioning: {
    id: "strategic_positioning", route: "flagship", kind: "report",
    tier: "Flagship", family: "brand_signal", objective: "Competitive positioning & messaging",
    title: "Strategic Positioning Report",
    description: "The flagship: category landscape, positioning x-ray, hero consistency and white space in one strategic arc.",
    sections: FLAGSHIP_SECTIONS,
  },
  social_benchmark: {
    id: "social_benchmark", route: "social", kind: "report",
    tier: "Core", family: "performance", objective: "Social content & engagement",
    title: "Social Content Benchmark",
    description: "How competitors use social and what actually earns engagement.",
    sections: [
      { key: "snapshot",          title: "Snapshot",              desc: "Who posts most, who earns most, dominant pillars and platforms." },
      { key: "territories",       title: "Territories & angles",  desc: "The core: pillars, and the angle each brand takes within them." },
      { key: "voice",             title: "Personality & voice",   desc: "Tone and archetype across brands, as the content reads." },
      { key: "declared_deployed", title: "Declared vs deployed",  desc: "Web/profile positioning vs what social actually does." },
      { key: "working",           title: "What's working",        desc: "Pillars, formats and posts that earn engagement — and why." },
      { key: "cadence",           title: "Cadence, format & platform", desc: "Posting rhythm and format/platform mix per brand." },
      { key: "takeaways",         title: "Takeaways",             desc: "ICP-lensed conclusions.", synthesis: true },
    ],
  },
  global_inspiration: {
    id: "global_inspiration", route: "global", kind: "report",
    tier: "Core", family: "quality", objective: "Creative inspiration & benchmarking",
    title: "Global Creative Inspiration",
    description: "Standout global cases — impressive for execution, craft and disruptive insight. NOT about moving the product into an innovation space (that's the Innovation Report).",
    sections: [
      { key: "rationale", title: "Curation rationale", desc: "What makes a case worth including." },
      { key: "cases",     title: "The cases",          desc: "A curated gallery: what it is, why it works, the transferable idea." },
      { key: "patterns",  title: "Patterns",           desc: "What recurs across the best cases." },
      { key: "plays",     title: "Transferable plays", desc: "Concrete moves for the client.", synthesis: true },
    ],
  },
  // ── New engine (to build — B10/F7) ──
  innovation: {
    id: "innovation", route: "innovation", kind: "report",
    tier: "Core", family: "brand_signal", objective: "Innovation scan",
    title: "Innovation Report",
    description: "How brands COMMUNICATE innovations and disruptive propositions — the message, not whether the content itself is novel. E.g. a brand announcing a geolocated community app for businesses.",
    built: false,
    sections: [
      { key: "innovation_map",   title: "Innovation map",        desc: "What innovations/disruptive propositions brands are communicating, and in what territories." },
      { key: "who_moves",        title: "Who's moving",          desc: "Which brands claim the innovation space and how credibly." },
      { key: "innovation_gaps",  title: "Gaps & open ground",    desc: "Innovation angles nobody is communicating yet." },
      { key: "exec",             title: "Executive read",        desc: "Strategic headline.", synthesis: true },
      { key: "recommendations",  title: "Recommendations",       desc: "Where to play in the innovation narrative.", synthesis: true },
    ],
  },

  // ── Section-extract cards (presets of the flagship) ──
  ex_landscape:   { id: "ex_landscape",   route: "flagship", kind: "section", coreKey: "landscape",   tier: "Section", family: "brand_signal", objective: "Category landscape map",            title: "Category landscape",         description: "The category territories and who owns what.",                 sections: sectionExtract("landscape") },
  ex_whitespace:  { id: "ex_whitespace",  route: "flagship", kind: "section", coreKey: "whitespace",  tier: "Section", family: "brand_signal", objective: "Identify white spaces / opportunities", title: "White space & opportunity", description: "Territories nobody owns → concrete opportunities.",           sections: sectionExtract("whitespace") },
  ex_hero:        { id: "ex_hero",        route: "flagship", kind: "section", coreKey: "hero",        tier: "Section", family: "brand_signal", objective: "Brand consistency audit",           title: "Hero & message consistency", description: "Whether the hero message holds over time and across channels.", sections: sectionExtract("hero") },
  ex_positioning: { id: "ex_positioning", route: "flagship", kind: "section", coreKey: "positioning", tier: "Section", family: "brand_signal", objective: "Tone & territory analysis",         title: "Positioning x-ray",          description: "Expressed vs validated positioning — the gap.",               sections: sectionExtract("positioning") },
};

// Objective → report card, for the Generate "Suggested" block (one card per objective).
export const OBJECTIVE_TO_CARD = Object.fromEntries(
  Object.values(REPORT_CARDS).filter((c) => c.objective).map((c) => [c.objective, c.id])
);

export const cardsForObjectives = (objectives = []) =>
  objectives.map((o) => REPORT_CARDS[OBJECTIVE_TO_CARD[o]]).filter(Boolean);

export const cardById = (id) => REPORT_CARDS[id] || null;
